[package]
name = "routee-compass-powertrain"
edition = "2021"
version.workspace = true
readme = "README.md"
license = "BSD-3-Clause"
description = "Crate providing integration between RouteE Compass and RouteE Powertrain"
homepage = "https://nrel.github.io/routee-compass"
repository = "https://github.com/NREL/routee-compass"
documentation = "https://docs.rs/routee-compass"
exclude = ["test", "**/.DS_Store", "target/"]

[dependencies]
bincode = { workspace = true }
config = { workspace = true }
env_logger = { workspace = true }
geo = { workspace = true }
itertools = { workspace = true }
kdam = { workspace = true }
log = { workspace = true }
ndarray = { workspace = true }
ninterp = { workspace = true }
ort = { workspace = true }
routee-compass-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smartcore = { workspace = true }
thiserror = { workspace = true }
uom = { workspace = true }
