[package]
name = "routee-compass-codegen"
version = "0.1.0"
edition = "2021"
description = "Code generation tools for RouteE Compass plugin development"
license = "BSD-3-Clause"

[[bin]]
name = "cargo-compass"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
heck = { workspace = true }
indoc = { workspace = true }
routee-compass = { workspace = true, default-features = false }
routee-compass-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
