[package]
name = "routee-compass-py"
edition = "2021"
version.workspace = true
readme = "README.md"
license = "BSD-3-Clause"
description = "Python bindings to the RouteE-Compass energy-aware routing engine"
homepage = "https://nrel.github.io/routee-compass"
repository = "https://github.com/NREL/routee-compass"
documentation = "https://docs.rs/routee-compass"
exclude = ["test", "**/.DS_Store", "target/"]

[lib]
name = "routee_compass_py"
crate-type = ["cdylib"]

[features]
default = ["routee-compass/default"]
ort-static = ["routee-compass/ort-static"]

[dependencies]
config = { workspace = true }
pyo3 = { version = "0.28.0", features = ["extension-module", "serde"] }
routee-compass = { workspace = true, default-features = false }
routee-compass-core = { workspace = true }
routee-compass-macros = { workspace = true }
serde_json = { workspace = true }
