[package]
name = "routee-compass-omf"
version = "0.3.1"
edition = "2021"
license = "BSD-3-Clause"
include = ["Cargo.toml", "README.md", "src/**/*.rs", "src/util/omf-defaults.toml"]
readme = "README.md"
repository = "https://github.com/NatLabRockies/routee-compass"
# documentation = "https://docs.rs/bambam-omf"
description = "OvertureMaps Foundation support for RouteE Compass"
categories = ["command-line-utilities", "science", "science::geo"]

[dependencies]

arrow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
csv = { workspace = true }
env_logger = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
geo = { workspace = true }
geozero = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
kdam = { workspace = true }
log = { workspace = true }
object_store = { workspace = true }
opening-hours-syntax = { workspace = true }
ordered-float = { workspace = true }
parquet = { workspace = true }
rayon = { workspace = true }
reqwest = { workspace = true }
routee-compass = { version = "0.19.3", path = "../routee-compass" }
routee-compass-core = { version = "0.19.3", path = "../routee-compass-core" }
# routee-compass-powertrain = { workspace = true }
serde = { workspace = true }
serde_arrow = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
uom = { workspace = true }
